### ISSUE TITLE
Whatsapp Number Banned

### ISSUE THREAD

**Issue by aniketjsg21** [dev-coco/WhatsApp-Batch-Unbanned-Tool#2]
respected Team

My number 9593000222 is banned and when i requested a review it was banned again, please help me out and recover my number please 
![WhatsApp Image 2024-01-23 at 5 41 34 PM](https://github.com/dev-coco/WhatsApp-Batch-Unbanned-Tool/assets/157488633/5276631f-b8b7-4fdb-b81e-8236b9cf6e54)

**Comment by dev-coco** [comment]
This problem is not related to this project.
